### PR TITLE
Feat/lint strategies with tsc

### LINKED ISSUE #69: interface definitions in readme are "fake typescript" and should be replaced with e.g. real typescript interfaces
- https://github.com/neume-network/strategies#extractor-strategy-interface-definition
- https://github.com/neume-network/strategies#transformer-strategy-interface-definition

### PR DESCRIPTION
**Pull request by TimDaub**
- fixes #69 
- Somehow I can't get to work where the module that is exported by extractor.mjs is linted by the extractor.d.ts file.
- Can JSON schema and TSC be used together somehow?

/cc @il3ven

### CODE REVIEW

**Comment by TimDaub** [comment]
But in a .ts file, could we import an extraction strategy such that it had to comply with the in .d.ts outlined type definition and fail if those weren't correctly implemented?

**Comment by il3ven** [comment]
We could do this in a .ts file.

```
class Transformer implements ITransformer {}
```

Where `ITransformer` is an interface as defined in the readme. If our class doesn't implement any function correctly then typescript will throw an error.

**Comment by TimDaub** [comment]
I don't like the idea of introducing tsc-code into the actual codebase. It was my goal with this PR to ensure the consistency and completeness of the strategy interfaces using a test that involves tsc. Someone over on another repo had an idea on how to use typing stubs to evaluate an interface and it looks a bit like what we need: https://github.com/TimDaub/better-sqlite3-session-store/issues/11#issuecomment-1179555482

**Comment by TimDaub** [comment]
closing, can be reopened when actively picked up again.

**Pull request closed without merging**
