### PR TITLE
Add call-contract-owner strategy

### LINKED ISSUE #197: Add strategy to track erc721 contract ownership addresses
- issue in schema repository: https://github.com/neume-network/schema/issues/24
- currently there are two ownership standards:
  - https://eips.ethereum.org/EIPS/eip-173
  - https://eips.ethereum.org/EIPS/eip-5313 although this one is compatible with 173
- Create a strategy that reduces the outcome (reducing optimizes the strategy as only a handful of contracts will have to be called) of e.g. web3subgraph to a set of contract addresses that are then called by their `function owner()`
- This ownership data may then later be augmented in the music-os-accumulator strategy

### PR DESCRIPTION
**Pull request by TimDaub**
- Fixes #197

### CODE REVIEW

**Comment by il3ven** [comment]
> Create a strategy that reduces the outcome (reducing optimizes the strategy as only a handful of contracts will have to be called) of e.g. web3subgraph to a set of contract addresses that are then called by their function owner()

Correct me if I am wrong. A reducer still needs to implemented?

**Comment by il3ven** [comment]
> Correct me if I am wrong. A reducer still needs to implemented?

Nevermind, found it. https://github.com/neume-network/strategies/blob/8851db0f2f4f50eff58f762c6100a206dbcbb39e/src/strategies/call-contract-owner/extractor.mjs#L53-L62

**Comment by neatonk** [comment]
Wow, that was quick! This is going to be sure useful.

**Pull request merged**
