### PR TITLE
fix bug where `0x` is returned for json rpc calls

### LINKED ISSUE #68: when passing old block number to soundxyz `tokenURI` strategy call, only `0x` is returned
- Could be a problem with rugpullindex.com's erigon node

### PR DESCRIPTION
**Pull request by il3ven**
Fixes #68 

Since this PR we are querying older blocks the cloudflare-eth does not work. We will need to use some other node in CI. However, I ran the tests locally and they work.

### CODE REVIEW

**Comment by TimDaub** [comment]
> Since this PR we are querying older blocks the cloudflare-eth does not work.

I'm fine with you merging this PR despite failing tests if, before, you create an issue about the above problem: CI failing because cloudflare-eth not allowing to go back further than 128 blocks.

**Comment by il3ven** [comment]
Created issue #92 and now merging this PR.

**Comment by TimDaub** [comment]
Did this PR work for you locally because with valid credentials for RPI node it won't work: https://github.com/neume-network/strategies/runs/6795248247?check_suite_focus=true#step:6:60 What node are you using?

**Comment by il3ven** [comment]
> Did this PR work for you locally?

Yes, it did. Let me check again.

**Comment by il3ven** [comment]
The error could be because of incorrect API key. We get the same error output when the key is wrong.

**Pull request merged**
