### PR TITLE
Sound Protocol  use `artist` instead of `artist_name` 

### PR DESCRIPTION
**Pull request by reimertz**
It seems Sound Protocol updated the metadata spec to use `artist` instead of `artist_name`

### CODE REVIEW

**Comment by reimertz** [comment]
Hi there @Kunkka0822 / @TimDaub. This PR should fix the missing Artist `name` for the new Sound Protocol property. 

Another test is the reason checks fail. 

```
✔ strategies › sound-protocol-get-tokenuri › transformer_test › sound-protocol-get-tokenuri transformer
```

**Comment by TimDaub** [comment]
> Hi there @Kunkka0822 / @TimDaub. This PR should fix the missing Artist `name` for the new Sound Protocol property.
> 
> Another test is the reason checks fail.
> 
> ```
> ✔ strategies › sound-protocol-get-tokenuri › transformer_test › sound-protocol-get-tokenuri transformer
> ```

ok it could be CI being flaky, I will get this merged and integrated asap.

**Comment by TimDaub** [comment]
> Another test is the reason checks fail.

yes, locally everything works, it's this issue:

- https://github.com/neume-network/strategies/issues/290

**Review by TimDaub — APPROVED** [review]
thank you <3

**Pull request merged**
